# Generated by Django 4.0.3 on 2022-03-21 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complementarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('direccion_imagen', models.TextField()),
                ('tipo_trabajo', models.CharField(choices=[('PROYECTO', 'Trabajo Escrito del Proyecto'), ('DIAGNOSTICO', 'Diagnostico Aplicado')], default='PROYECTO', max_length=20)),
                ('descripcion', models.TextField()),
                ('direccion', models.TextField()),
                ('publicado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
